name: chrono_dart
description: Chrono in dart. Inspired by @wanasit/chrono.
version: 1.0.0
repository: https://github.com/g-30/chrono_dart

environment:
  sdk: ^3.1.0

dependencies:
  day: ^0.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.6
