name: chrono_dart
description: A natural language date parser in Dart. Finds date references in user-generated text and returns objects containing DateTime and position in text.
version: 2.0.1
repository: https://github.com/g-30/chrono_dart

environment:
  sdk: ^3.1.0

dependencies:
  day: ^0.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.6
